# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5c02b5553d53ae6c69d2cfc543276a89"
name = "Meta Volume Discount"
handle = "meta-volume-discount"
application_url = "https://metafield-volume-discount-app.onrender.com/"
embedded = true

[build]
dev_store_url = "brewmart-dev-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://metafield-volume-discount-app.onrender.com/auth/callback",
  "https://metafield-volume-discount-app.onrender.com/auth/shopify/callback",
  "https://metafield-volume-discount-app.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[pos]
embedded = false
